/* 自動生成ファイル - 直接編集しないでください。events.json から自動生成されます。 */
window.__EVENTS__ = {
  "updatedAt": "2026-09-18",
  "targetPeriod": "2026年9月19日(土)・20日(日)・21日(月・敬老の日)",
  "isSampleData": false,
  "criteria": {
    "residence": "横浜市神奈川区",
    "origin": "横浜駅",
    "range": "電車で約1時間圏内(川崎・大和など横浜市外もOK)。ブルーライン沿線・相鉄線沿線・JR30分圏内を優先",
    "family": "3歳の子どもを含む家族3人",
    "budget": "有料でもOK(無料・低価格も歓迎)",
    "venue": "屋内・屋外どちらでもOK",
    "priority": "無料/低価格イベント、地域の子育て支援・親子向けイベント",
    "targetDays": "毎週の土曜・日曜・祝日"
  },
  "events": [
    {
      "title": "こどもの国(敬老の日3連休スペシャル)",
      "area": "青葉区・こどもの国",
      "place": "こどもの国",
      "datetime": "9月19日(土)〜21日(月・祝) 9:30〜16:30(最終入園15:30)。9/19〜23は中央広場にキッチンカーが出店、9/21(敬老の日)は65歳以上入園無料",
      "access": "横浜駅→東急東横線・田園都市線・こどもの国線経由でこどもの国駅まで約50分、駅から徒歩3分",
      "price": "大人800円 / 3歳以上の幼児200円(2歳以下無料)",
      "isFree": false,
      "isSat": true,
      "isSun": true,
      "isHoliday": true,
      "isNear": false,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "広大な敷地に遊具・牧場などが揃う定番の親子お出かけスポット。3連休中はキッチンカーが多数出店し、敬老の日は祖父母(65歳以上)の入園が無料になります。",
      "kidPoint": "3連休で混雑が予想されます。地元・青葉区主催の「GREEN×EXPO 2027開催半年前記念イベント」が9/19に園内周辺で行われる情報もありますが、内容・時間の詳細は確認できませんでした。遊具の多くは屋外のため雨天時は楽しめる範囲が限られます。",
      "needsCheck": true,
      "checkReason": "「GREEN×EXPO 2027開催半年前記念イベント」の9/19の具体的な開催内容・時間、キッチンカーの出店時間帯が情報源で確認できませんでした。",
      "url": "https://www.kodomonokuni.org/calendar/"
    },
    {
      "title": "横浜・八景島シーパラダイス「花火シンフォニア」",
      "area": "金沢区・八景島",
      "place": "横浜・八景島シーパラダイス",
      "datetime": "9月19日(土)・20日(日)・21日(月・祝) 20:30〜20:40(約10分間、デジタル制御で花火と音楽がシンクロ)",
      "access": "横浜駅から京急本線快特で金沢八景駅まで、シーサイドラインに乗り換え八景島駅まで約34分、駅から徒歩すぐ",
      "price": "入島無料。無料観覧エリアあり。花火が見やすい有料観覧席・優先エリアもあり(具体的な料金は要確認)",
      "isFree": true,
      "isSat": true,
      "isSun": true,
      "isHoliday": true,
      "isNear": false,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "約2,500発の花火と音楽がコンマ1秒単位でシンクロするシーパラダイスオリジナルの花火ショー。3日連続開催。",
      "kidPoint": "開始が20:30と遅めのため、3歳児は眠くなる時間帯です。混雑が予想されるためベビーカーより抱っこ紐が便利です。",
      "needsCheck": true,
      "checkReason": "有料観覧席の具体的な料金が情報源で確認できませんでした。",
      "url": "https://www.seaparadise.co.jp/"
    },
    {
      "title": "横浜ナイトフラワーズ2026(大さん橋)",
      "area": "中区・大さん橋",
      "place": "大さん橋周辺(横浜港)",
      "datetime": "9月20日(日) 19:00〜19:05(約5分間)",
      "access": "みなとみらい線「日本大通り」駅から徒歩約5分(横浜駅からは電車+徒歩で合計約20〜25分)",
      "price": "無料",
      "isFree": true,
      "isSat": false,
      "isSun": true,
      "isHoliday": false,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "横浜港周辺で短時間打ち上がる花火演出。指定観覧席はなく、周辺エリアから自由に鑑賞できます。",
      "kidPoint": "19時開始で5分間のみのため、3歳児が飽きる前に終わります。ただし夕食・お風呂の時間との兼ね合いに注意してください。人混みが予想されるため見物場所は早めに確保することをおすすめします。",
      "needsCheck": false,
      "checkReason": "",
      "url": "https://www.welcome.city.yokohama.jp/eventinfo/ev_detail.php?bid=yw11005"
    },
    {
      "title": "プリンフェス in ららぽーと横浜",
      "area": "都筑区・鴨居(JR横浜線)",
      "place": "ららぽーと横浜 1Fサウスコート・セントラルガーデンKiLaLa",
      "datetime": "9月19日(土)〜23日(水・祝) 10:00〜18:00。9/20(日)は「ポムポムプリン30周年スペシャルステージ」を13:00・16:00の2回開催",
      "access": "横浜駅からJR横浜線で鴨居駅まで約18分、駅から徒歩7分(合計約25分)",
      "price": "入場無料(だきつきプリン体験・グッズ購入・ジェルキャンドルワークショップ等は別途料金の可能性あり)",
      "isFree": true,
      "isSat": true,
      "isSun": true,
      "isHoliday": true,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": true,
      "note": "ポムポムプリン30周年を記念し、全国のプリン屋さんが出店するグルメ&キャラクターイベント。大きなポムポムプリンとの「だきつきプリン」撮影や、サンリオカフェワゴンも登場します。",
      "kidPoint": "屋内モールのため雨天でも安心です。9/20のステージイベントは整理券配布制の可能性があるため、参加希望の場合は早めの来場がおすすめです。",
      "needsCheck": true,
      "checkReason": "ジェルキャンドルワークショップの参加費・事前予約要否、ステージイベントの整理券配布方法・時間が情報源で確認できませんでした。",
      "url": "https://mitsui-shopping-park.com/lalaport/yokohama/event/3601362.html"
    },
    {
      "title": "グリーンワークショップ「菜の花の種まき&お花を探そう」",
      "area": "旭区・二俣川(相鉄線)",
      "place": "ジョイナステラス二俣川",
      "datetime": "9月19日(土)(開催時間は情報源で確認できませんでした)",
      "access": "相鉄本線で横浜駅から二俣川駅まで約15分、駅から徒歩2分(建物内直結)",
      "price": "無料と思われますが要確認",
      "isFree": true,
      "isSat": true,
      "isSun": false,
      "isHoliday": false,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "施設内のグリーンスペースで行われる、菜の花の種まきや花探しを楽しむ親子向けワークショップ。",
      "kidPoint": "開催時間、参加費、事前予約要否の詳細が公式サイトで確認できませんでした。小さなお子様と一緒に土いじりができる貴重な機会です。",
      "needsCheck": true,
      "checkReason": "開催時間、参加費、事前予約要否の詳細が情報源で確認できませんでした。",
      "url": "https://joinus-terrace.com/eventnews/"
    },
    {
      "title": "ママHOLIDAYフェスタ横浜",
      "area": "中区・山下町",
      "place": "横浜産貿ホール マリネリア",
      "datetime": "9月19日(土) 10:00〜16:00",
      "access": "横浜駅東口バスターミナルから市営バスで約15分、またはみなとみらい線「日本大通り」駅から徒歩5分(横浜駅からは合計約20分)",
      "price": "入場無料(要来場予約・LINE等での事前予約制)",
      "isFree": true,
      "isSat": true,
      "isSun": false,
      "isHoliday": false,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": true,
      "note": "赤ちゃん〜未就学児向けの「ごろりんレース」「ハイハイレース」「よちよちレース」などの体験型コンテンツ、企業ブース、スタンプラリー、お菓子まきが行われるママ向けイベント。",
      "kidPoint": "事前の来場予約(LINE)が必要です。よちよちレースなど3歳児が参加できそうなコンテンツもありますが、具体的な年齢区分は確認できませんでした。屋内会場のため雨天でも安心です。",
      "needsCheck": true,
      "checkReason": "3歳児が参加できる具体的なレースの年齢区分、各コンテンツが無料か有料かの詳細が情報源で確認できませんでした。",
      "url": "https://mamaholi.oliolimama.net/mamaholiday_yokohama/"
    },
    {
      "title": "川崎・沖縄オリオン祭2026",
      "area": "川崎市川崎区",
      "place": "川崎競馬場 内馬場広場・サンサン広場",
      "datetime": "9月19日(土) 10:00〜16:00・17:15〜20:30、9月20日(日)・21日(月・祝) 各10:00〜16:00",
      "access": "JR東海道線・京浜東北線で横浜駅から川崎駅まで約9分、川崎駅から無料シャトルバスで約10〜15分(合計約20〜25分)",
      "price": "無料",
      "isFree": true,
      "isSat": true,
      "isSun": true,
      "isHoliday": true,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "エイサーや沖縄ポップスなどのステージパフォーマンス、沖縄フード・物産展、ワークショップが楽しめる交流イベント。3日連続開催。",
      "kidPoint": "屋外開催のため日中の暑さ対策と休憩場所の確認をおすすめします。19日夜の部(17:15〜20:30)は3歳児には遅い時間帯です。",
      "needsCheck": false,
      "checkReason": "",
      "url": "https://www.kawasakicity.info/kawasaki-okinawa-orion-festival-2026/"
    },
    {
      "title": "臨港パークフリーマーケット",
      "area": "西区・みなとみらい",
      "place": "臨港パーク(南口広場)",
      "datetime": "9月21日(月・祝) 10:00〜16:00",
      "access": "みなとみらい線「みなとみらい」駅から徒歩5分(横浜駅からは電車+徒歩で合計約15分)",
      "price": "入場無料(掘り出し物の購入は別途)",
      "isFree": true,
      "isSat": false,
      "isSun": false,
      "isHoliday": true,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "海と緑に囲まれた臨港パークで行われる約100店舗規模のフリーマーケット。キッチンカーも出店。",
      "kidPoint": "広い芝生広場があるため小さな子どもが動き回っても安心です。日除けが少ないため熱中症対策をおすすめします。",
      "needsCheck": false,
      "checkReason": "",
      "url": "https://recyclekanagawa.com/place/rinkai/"
    },
    {
      "title": "日産スタジアムBIGフリマ",
      "area": "港北区・新横浜",
      "place": "日産スタジアム",
      "datetime": "9月21日(月・祝) 10:00〜16:00",
      "access": "JR横浜線で横浜駅から小机駅まで約20分、駅から徒歩7分(合計約27分)。または横浜市営地下鉄ブルーラインで新横浜駅から徒歩12分",
      "price": "入場無料",
      "isFree": true,
      "isSat": false,
      "isSun": false,
      "isHoliday": true,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "衣類・生活雑貨・子供用品など幅広い出店がある県内最大級規模のフリーマーケット。車ごと出店もあり大型家具・家電も並びます。",
      "kidPoint": "屋外の広いスタジアム敷地での開催のため、ベビーカーでの移動もしやすいです。日除けが少ないため熱中症対策を。",
      "needsCheck": false,
      "checkReason": "",
      "url": "https://recyclekanagawa.com/place/%E6%97%A5%E7%94%A3%E3%82%B9%E3%82%BF%E3%82%B8%E3%82%A2%E3%83%A0-big-%E3%83%95%E3%83%AA%E3%83%BC%E3%83%9E%E3%83%BC%E3%82%B1%E3%83%83%E3%83%88/"
    },
    {
      "title": "馬車道エキナカフリマ",
      "area": "中区・馬車道",
      "place": "馬車道駅 地下1階",
      "datetime": "9月19日(土) 10:00〜15:00",
      "access": "みなとみらい線「馬車道」駅地下1階(横浜駅からは電車で約10分)",
      "price": "入場無料",
      "isFree": true,
      "isSat": true,
      "isSun": false,
      "isHoliday": false,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": true,
      "note": "駅構内で開催される完全屋内のフリーマーケット。衣類や小物など最大60店舗が出店します。",
      "kidPoint": "屋内・駅直結のため、雨の日でも安心してベビーカーで立ち寄れます。天候に左右されない選択肢です。",
      "needsCheck": false,
      "checkReason": "",
      "url": "https://recyclekanagawa.com/place/%E9%A6%AC%E8%BB%8A%E9%81%93/"
    },
    {
      "title": "ハンドメイドマルシェ in 横浜スタジアム",
      "area": "中区・関内",
      "place": "横浜スタジアム(BASEGATE横浜関内近辺)",
      "datetime": "9月20日(日) 10:00〜16:00",
      "access": "横浜駅からJR根岸線で関内駅まで約7分、駅から徒歩数分(合計約15分)",
      "price": "入場無料",
      "isFree": true,
      "isSat": false,
      "isSun": true,
      "isHoliday": false,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "ハンドメイド作家の作品が集まるマルシェ。アットホームな雰囲気で世界にひとつだけの品と出会えます。",
      "kidPoint": "開催会場がスタジアム内(屋内)か周辺の屋外広場かが情報源で明確に確認できませんでした。",
      "needsCheck": true,
      "checkReason": "開催会場が屋内(スタジアム内)か屋外(周辺広場)か情報源で明確に確認できませんでした。",
      "url": "https://www.enjoytokyo.jp/event/2074687/"
    },
    {
      "title": "あざみ野 親子のフリーゾーン",
      "area": "青葉区・あざみ野(ブルーライン)",
      "place": "横浜市民ギャラリーあざみ野(アートフォーラムあざみ野) 3Fアトリエ",
      "datetime": "9月21日(月・祝) 10:00〜11:30",
      "access": "横浜市営地下鉄ブルーラインで横浜駅からあざみ野駅まで約40分、駅から徒歩約5分",
      "price": "1人300円(子ども・大人とも、当日支払い)",
      "isFree": false,
      "isSat": false,
      "isSun": false,
      "isHoliday": true,
      "isNear": false,
      "isWithinHour": true,
      "isIndoor": true,
      "note": "粘土・紙・絵の具を使って自由に創作できる、未就学児〜小学生とその保護者向けのプログラム。",
      "kidPoint": "事前予約制(2026年8月22日10時から先着順で受付開始、各回先着30組)のため、すでに定員に達している可能性があります。参加希望の場合は主催者に空き状況を確認してください。屋内のため雨天でも安心です。",
      "needsCheck": true,
      "checkReason": "予約受付が既に締め切られ満員になっている可能性があり、当日の空き状況が確認できませんでした。",
      "url": "https://artazamino.jp/event/post-24084"
    },
    {
      "title": "横浜ランタンナイト2026",
      "area": "横浜駅東口・みなとみらい",
      "place": "横浜ベイクォーター 3Fメインプラザほか",
      "datetime": "5月30日(土)〜9月23日(水・祝)開催中(9月19日(土)・20日(日)・21日(月・祝)も開催)、10:00〜23:00、ライトアップ17:00〜",
      "access": "横浜駅東口から徒歩約5分",
      "price": "無料",
      "isFree": true,
      "isSat": true,
      "isSun": true,
      "isHoliday": true,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "約1,000個のランタンが昼夜で表情を変える装飾イベント。今年は20周年スペシャルバージョンとして開催中です。9/23の会期終了が近づいています。",
      "kidPoint": "横浜駅から徒歩圏内で気軽に立ち寄れます。夜のライトアップ(17時以降)は幻想的ですが、3歳児の夕食・就寝時間を考慮して訪問時間を検討してください。",
      "needsCheck": true,
      "checkReason": "子供向け体験プログラム(ランタン絵付け体験等)の9/19〜21の実施有無や参加費が情報源で確認できませんでした。",
      "url": "https://www.yokohama-bayquarter.com/event/detail/98"
    },
    {
      "title": "サンバフェスタ〜サンバとブラジル料理を楽しもう!〜",
      "area": "横浜駅東口・みなとみらい",
      "place": "横浜ベイクォーター",
      "datetime": "9月21日(月・祝)(開催時間は情報源で確認できませんでした)",
      "access": "横浜駅東口から徒歩約5分",
      "price": "情報源で確認できませんでした(無料の可能性が高い)",
      "isFree": false,
      "isSat": false,
      "isSun": false,
      "isHoliday": true,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": false,
      "note": "サンバとブラジル料理を楽しめる異文化交流イベント。",
      "kidPoint": "開催時間、具体的な会場(屋内外)、料金の詳細が情報源で確認できませんでした。訪問前に公式サイトでの確認をおすすめします。",
      "needsCheck": true,
      "checkReason": "開催時間、具体的な会場(屋内外)、料金について情報源で確認できませんでした。",
      "url": "https://www.yokohama-bayquarter.com/event/"
    },
    {
      "title": "横浜アンパンマンこどもミュージアム ハロウィンイベント",
      "area": "西区・みなとみらい",
      "place": "横浜アンパンマンこどもミュージアム&モール",
      "datetime": "9月14日(月)〜10月31日(土)開催中(9/19・20・21も開催)。日時指定入館制",
      "access": "横浜駅からみなとみらい線・JR根岸線等で新高島駅・桜木町駅方面まで約5〜10分、駅から徒歩8〜15分(合計約15〜20分)",
      "price": "2・3Fミュージアム入館料は1歳以上2,200円〜2,800円(税込・日時指定WEBチケットの事前購入必須)。1Fショップ&フードは入場無料",
      "isFree": false,
      "isSat": true,
      "isSun": true,
      "isHoliday": true,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": true,
      "note": "ハロウィン仮装のアンパンマンたちと過ごせる期間限定イベント。ハロウィンお面工作なども実施予定です。",
      "kidPoint": "完全屋内施設のため天候に左右されず楽しめます。事前の日時指定WEBチケット購入が必須で、9/20入館分から料金改定予定のため、予約時に最新料金を確認してください。",
      "needsCheck": true,
      "checkReason": "9/20からの料金改定後の正確な料金、当日の混雑状況・チケット残数が情報源で確認できませんでした。",
      "url": "https://www.yokohama-anpanman.jp/"
    },
    {
      "title": "かなーちえ 親子あそびひろば",
      "area": "神奈川区",
      "place": "神奈川区地域子育て支援拠点 かなーちえ(東神奈川1-29 東部療育ビル3階)",
      "datetime": "9月19日(土) 9:30〜15:30(日曜・月曜・祝日は休館)",
      "access": "横浜駅からJR京浜東北線・根岸線で東神奈川駅まで約3分、駅から徒歩3分(合計約10分)",
      "price": "無料",
      "isFree": true,
      "isSat": true,
      "isSun": false,
      "isHoliday": false,
      "isNear": true,
      "isWithinHour": true,
      "isIndoor": true,
      "note": "神奈川区の地域子育て支援拠点で開かれる、乳幼児と保護者向けの自由あそびひろば。おもちゃや絵本が揃い、雨の日でも安心して過ごせます。スタッフに子育て相談もできます。",
      "kidPoint": "休館日が日・月・祝日のため、この3連休で利用できるのは19日(土)のみです。事前登録が推奨されています。横浜駅から一番近く、天候に左右されない選択肢です。",
      "needsCheck": true,
      "checkReason": "9/19当日の具体的なプログラム内容や混雑状況は公式サイト(kana-chie.com)で確認できず、通常開館時間のみ確認できました。",
      "url": "https://kana-chie.com/"
    },
    {
      "title": "体験参加型リズムアトラクション「ドラミングハイ!」",
      "area": "川崎市高津区・溝の口",
      "place": "高津市民館(プラザ橘) 大ホール",
      "datetime": "9月19日(土) 13:30〜14:30",
      "access": "横浜駅から東急東横線・田園都市線経由で溝の口駅・武蔵溝ノ口駅まで約41分、駅から徒歩数分",
      "price": "情報源で確認できませんでした",
      "isFree": false,
      "isSat": true,
      "isSun": false,
      "isHoliday": false,
      "isNear": false,
      "isWithinHour": true,
      "isIndoor": true,
      "note": "段ボールドラムを使い、指揮者(ファシリテーター)のリードに合わせてみんなでリズムを作っていく観客参加型の打楽器アトラクション。小学生以下の子どもと保護者500名が対象。",
      "kidPoint": "3歳児でも参加できる可能性がありますが、対象年齢の下限、参加費、事前申込方法の詳細が確認できませんでした。屋内ホールのため雨天でも安心です。",
      "needsCheck": true,
      "checkReason": "対象年齢の下限、参加費、事前申込方法の詳細が情報源で確認できませんでした。",
      "url": "https://www.kawasaki-takatsu.jp/shiminkan/"
    }
  ]
}
;
